### ISSUE TITLE
Suddenly unable to login

### ISSUE THREAD

**Issue by koshisan** [etheralm/libpurecool#12]
I set up some bash scripts for integrating the example scripts from the documentation into my openhab installation (no python knowledge at all, so it was easier than writing a script with parameter handling).
Everything was working nicely until yesterday it suddenly stopped. Running the scripts manually gives a "Unable to login to Dyson account" because dyson_account.login() returns false - but I cant really see how to get additional debugging info. The login credentials are unchanged. The Android app is also still working with the same credentials.
I thought the folks at Dyson might have changed the login server and found this post: https://github.com/CharlesBlonde/libpurecoollink/issues/29 - however, even changing the API server  doesn't seem to solve my problem...

**Comment by etheralm** [comment]
Hi, 

Can you please provide a bit more information, which version are you using in your bash scripts?

**Comment by koshisan** [comment]
Hi!
Of course, thanks for getting back to me so quickly and for your work in general!

I installed the library using pip last weekend. Is that not the latest one?

I skipped through the .py files under /usr/local/lib/python3.6/dist-packages/libpurecool, but couldn't find a version number...

Just in case that version was outdated I just downloaded the git and overwrote the file from pip with the latest version - however, the error is still the same.

**Comment by etheralm** [comment]
I pushed a new version 2 days ago in pypi that contains the fix with the new API url.  You can check the version of the pypi package by running `pip show libpurecool`. The latest latest version is 0.6.1.

One thing that I noticed is that some people have issues connecting when using a different language for the dyson account. Can you try to connect to the dyson API by using 'GB'  for language string like this: `DysonAccount("<dyson_account_email>","<dyson_account_password>","GB")`

Let me know if that helps.

**Comment by koshisan** [comment]
Witchcraft! Seems like it was on Version 0.6.0. I upgraded to 0.6.1 and got it running again. With different python versions installed on the system I might just have edited the wrong files with my manual attempts...
The third parameter is for the language? I was under the impression that it would have to be set according to your region (because that is what the official app is asking at login). Currently I have it set to JP, because that is where I live. I am using the offical app in German, though - so I might be a complicated case ;)
But since it is working the issue can be closed in my opinion. Thanks again! :)

**Comment by etheralm** [comment]
It seems to be working with `GB` for the language string even if you are using another language for the mobile app. I'm not exactly sure what that parameter is supposed to do in their API to be honest, but if it works with another string for language for you, leave it as it is, no need to switch.

Glad to hear that it's working now. I'll close the issue.

**Comment by charlesnadeau** [comment]
I upgraded to version 0.6.1 and I still can't log in. I get an error message saying:

/usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

Is there a way to log all the communication between the program and the API's site to help debugging?

I run python version 3.6.9 and urllib3 version 1.22. My Purifier Cool Tower runs software version 21.04.03 and it my program communication with it stopped working on February 3rd at 4pm GMT+1.

Thanks for your help.

Charles

**Comment by etheralm** [comment]
The InsecureRequestWarning from urllib is normal since dyson are using a self signed certificate. It wouldn't normally be an issue, but you shoudn't be getting it since I disabled the ssl verification in the api call. Did you install it from pypi, or did you clone the repo, also is this the only error/warning that you see?

**Comment by charlesnadeau** [comment]
I installed it using pip:
`sudo -H pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org libpurecool`
Yes, it is the only error/warning I see.
Thanks!

Charles
